pipeline {
//  agent { label 'linux' }
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  environment {
    DOCKERHUB_CREDENTIALS = credentials('gide100-dockerhub')
    DOCKER_HOST='unix:///var/run/docker.sock'
    DOCKER_TLS_VERIFY = ''
    DOCKER_CERT_PATH = ''
  }
  stages {
    stage('Test Docker Access') {
      steps {
        unset DOCKER_TLS_VERIFY
        unset DOCKER_CERT_PATH
        sh 'docker version'
      }
    }
    stage('Build') {
      steps {
        unset DOCKER_TLS_VERIFY
        unset DOCKER_CERT_PATH
        sh 'docker build -t gide100/gn-alpine:latest .'
      }
    }
    stage('Login') {
      steps {
        unset DOCKER_TLS_VERIFY
        unset DOCKER_CERT_PATH
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        unset DOCKER_TLS_VERIFY
        unset DOCKER_CERT_PATH
        sh 'docker push gide100/gn-alpine:latest'
      }
    }
  }
  post {
    always {
      unset DOCKER_TLS_VERIFY
      unset DOCKER_CERT_PATH
      sh 'docker logout'
    }
  }
}
